services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"         
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: EMproject
      MYSQL_USER: user
      MYSQL_PASSWORD: Password123
    command: [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass123"]
      interval: 5s
      timeout: 3s
      retries: 30

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"              
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass123
      UPLOAD_LIMIT: 256M

volumes:
  db_data: